USE HimalayanExpeditionsDW;
GO

DROP TABLE IF EXISTS BRIDGE_ExpeditionMembers;
DROP TABLE IF EXISTS FACT_Expeditions;
DROP TABLE IF EXISTS DIM_CountryIndicators;
DROP TABLE IF EXISTS DIM_Member;
DROP TABLE IF EXISTS DIM_HostCountry;
DROP TABLE IF EXISTS DIM_ExpeditionStatus;
DROP TABLE IF EXISTS DIM_Route;
DROP TABLE IF EXISTS DIM_Peak;
DROP TABLE IF EXISTS DIM_Nationality;
DROP TABLE IF EXISTS DIM_Date;
