USE HimalayanExpeditionsDW;
GO

DROP TABLE IF EXISTS FACT_MemberExpedition;
DROP TABLE IF EXISTS DIM_Expedition;
DROP TABLE IF EXISTS DIM_CountryIndicator;
DROP TABLE IF EXISTS DIM_Peak;
DROP TABLE IF EXISTS DIM_Date;
